### PR TITLE
Expose setQuota credentials method via PerspectiveBroker Proxy

### LINKED ISSUE #653: Expose setQuota in HTTP API
Hello, 

I need the possibility to reset quota value via HTTP API and as far I understand it cannot be done in current version of code. There is `user_update_quota `method in `RouterPBProxy` object, but it increments supplied value instead of resetting it. 

I'm going to implement that behavior and wanna ask how to do that better?
a) expose PB's `setQuota` method via HTTP API
b) pass an extra parameter (replace=False by default) to `updateQuota` to allow completely replace the old value

I personally prefer the second solution.
Thanks

### PR DESCRIPTION
**Pull request by mexicarne**
updateQuota allows to increase or decrease quota value, but there is
want to also allow to replace existing quota value with one provided
by user.

This change resolves #653

### CODE REVIEW

**Comment by farirat** [comment]
@mexicarne thank you for this contrib !

Could you please cover this addition with a test ? it should go here: https://github.com/jookies/jasmin/blob/master/jasmin/routing/test/test_router.py

**Comment by mexicarne** [comment]
Sorry for delay. Sure, will do.

**Comment by mexicarne** [comment]
Just done, sorry for delay.

**Comment by mexicarne** [comment]
I added them into `test_increase_decrease_quota()` and they run successfully. Or should I put them into it's own test function?

**Comment by farirat** [comment]
merged to upcoming release (0.9.28)

**Comment by mexicarne** [comment]
Great, thank you!

**Pull request merged**
