### PR TITLE
Exposed AMQP heartbeat setting

### PR DESCRIPTION
**Pull request by terrycain**
After pointing jasmin at a loadbalancer to a set of mirrored RabbitMQ servers, the loadbalanacer was dropping the connection as it would go idle for long periods (which seems like a real common problem on google and everyone suggesting turning on heartbeat in the client).

Digging into `txamqp`, I found that the constructor [here](https://github.com/txamqp/txamqp/blob/master/src/txamqp/protocol.py#L240) took a heartbeat parameter, so I just exposed that and added a config option. It defaults to `0` which is off, otherwise its an interval of heartbeats.

I have it currently running in AWS, pointing to an ELB with an idle timeout of 2 minutes and a heartbeat interval of 30 seconds. Its been going for 4 hours now with no issues, before this it was dropping the connection and reconnecting every 2 minutes so I think were onto a winner.

Also `dlr.cfg` was missing an AMQP section so I added it.

### CODE REVIEW

**Comment by terrycain** [comment]
Ok Im pretty sure someone broke the tests as all of master is failing in travis

**Comment by farirat** [comment]
@terrycain confirmed, all tests went broken after latest update on travis-ci, am working on it right now, will accept this PR just after fixing the broken tests.

**Comment by terrycain** [comment]
Thanks :smile:, and I still intend to fixup #615, hopefully I'll get some time over christmas.

**Comment by terrycain** [comment]
Cheers, don't suppose you know when this will be available on pypi?

**Comment by farirat** [comment]
already packaged for pypi, deb and rpm.

Docker build is ongoing.

**Comment by terrycain** [comment]
Ahh my bad, I think when I searched for it google just gave me 0.9.25, its in 0.9.26 :smile: thanks.

**Pull request merged**
