### PR TITLE
Migrate to Python3

### PR DESCRIPTION
**Pull request by DomAmato**
This is a huge PR but from what I can tell it works.
It required upgrading several dependencies which them themselves have open PRs. 
I removed the vendor folder as maintaining them in this repo is only adding extra work. 

The test folders I also consolidated just for convenience of not having to dig through the source folders to find the one test file.

There is no python 2 compatibility here, python 2 is no longer supported and backwards compatibility was not worth the added complexity in maintaining.

### CODE REVIEW

**Comment by farirat** [comment]
Hey @DomAmato, thanks for this **huge contribution** !

Definitely a hard work porting jasmin to py3, great work.

Let's run the tests and check the merging possibilities

**Comment by farirat** [comment]
Tried to make the tests pass with no luck.

Went reading your work and since i have some issues to build the branch, i have some questions for you:
- Did you remove some tests ?
- Did you add extra tests ?
- Is this backward compatible with py2 ?

As for the vendorized dependencies under **vendo/** i've seen you put them into separate repositories and that's a good/clean approach, i will put them under https://github.com/jookies once we get this PR passing, please share your email with me (bruno.chaudhary@jookies.net).

**Comment by DomAmato** [comment]
I added skips on a few tests, one that broke a general rule (it depended on another test to complete for it to even work) and all the korean encoding ones because the kcr5601 encoding in python is not compatible with the code map specification for SMPP.

I think I added one extra test

It is not backwards compatible with python 2. Python 2 had its end of life 5 months ago, any new code shouldn't bother with compatibility as legacy systems can pin their version to one that works for them.

As for having the tests pass, I had 3 failures on mine but when I run those tests individually they pass or if I even test the whole file or module they are in they pass. It is only when the full test suite is run do they fail so I felt that was more a problem with the tests not cleaning up after themselves properly than an issue with those particular tests

**Comment by DomAmato** [comment]
I will clean this up a little. There are some dev artifacts that I can remove that are not integral to the PR

**Comment by farirat** [comment]
Hey @DomAmato 

Can you confirm you can successfully clone this PR ?

I'm stuck on this error while pip installing the requirements:

> Obtaining txAMQP from git+https://github.com/DomAmato/txamqp.git@master#egg=txAMQP (from -r requirements.txt (line 15))
  Updating ./venv3/src/txamqp clone (to revision master)
  Running command git fetch -q --tags
  Running command git reset --hard -q 837e452319ffe2635acdef34bce7f468a50bb079
  error: unable to create symlink README.md: File name too long
  fatal: Could not reset index file to revision '837e452319ffe2635acdef34bce7f468a50bb079'.
ERROR: Command errored out with exit status 128: git reset --hard -q 837e452319ffe2635acdef34bce7f468a50bb079 Check the logs for full command output.

**Comment by DomAmato** [comment]
hmm not really sure since it installs fine in every containerized instance and your virtual environment should be no different. Ideally the maintainer of txamqp would merge in changes and then installation wont require cloning it from github.

**Comment by DomAmato** [comment]
Hey its been awhile and just wanted to check in if there was more you needed me to do. So far it has been running well for us as I got it so that we can deploy new configurations that work within our CI environment, I even added some extra features that are somewhat specific to our use case like reading from an AWS SQS queue though I did that in a separate branch

**Comment by soufiane-bouchaara** [comment]
Hi @farirat @DomAmato ,

Any news about this PR ? we are waiting for this huge release

**Comment by DomAmato** [comment]
@soufiane-bouchaara I haven't heard from @farirat since he last posted in this thread unfortunately. However the python 3 version of jasmin is currently running in our production environment so if you want you can use my fork for the time being. the setup is not quite as easy since it installs from git urls but I can help if you have any questions

**Comment by farirat** [comment]
@DomAmato working on this PR through the 0.10.0 branch https://github.com/jookies/jasmin/tree/0.10.0

**Pull request merged**
