### PR TITLE
Add support for schedule-delivery-time to http api and the smpp manager.

### PR DESCRIPTION
**Pull request by JamuelStarkey**
I've added support for schedule-delivery-time to the http api and then enabled it as well on the smpp side.  This is my first foray into Github so please forgive me if I'm not proposing my change correctly.

In any case I've tested out my change against 0.9.15-1. on CentOS7 against Level-3's SMMP lab server.

### CODE REVIEW

**Comment by farirat** [comment]
Brilliant work @JamuelStarkey ! thanks for this contrib.

I would suggest you the following to get the PR correctly merged:

1. Please merge to 0.9rc16 instead of master, 0.9rc16 is the target release for now,
2. **schedule-delivery-time** is too long for a http arg, i would consider shortening it to **sdt** or simply **tts** (time to send),
3. Good work for the documentation cover, i would also test cover the newly introduced argument, i'll give you the shortcuts where to test below.

Testing the new arg:
1. In http api, we need to ensure the new arg is optional, only integer, etc ...
Take a look [here](https://github.com/jookies/jasmin/blob/master/jasmin/protocols/http/test/test_server.py#L277), that's how i tested the new **tag** arg in the http api _scope_.
2. In the router, we need to test the sent **submit_sm** over smpp has the correct **schedule-delivery-time** previously defined in the http api.
Take a look [here](https://github.com/jookies/jasmin/blob/master/jasmin/routing/test/test_routing_submit_sm_and_dlr.py#L37), that's an example showing how to test validity period in submit_sm and compare it with the original value set in the http api while sending the message.

**Comment by JamuelStarkey** [comment]
@farirat -- I've been working on adding the changes that you've recommended.  To that end I'm having some trouble with the travis ci test cases.  

Specifically in creating coverage for whether the schedule delivery time http param now called "sdt" is optional.  I tried creating the test with the sdt param not specified and checking for assertEqual 200 but travis did not like that:

`    @defer.inlineCallbacks`
`    def test_send_with_sdt(self):`
`        params = {'username': self.username,`
`                  'password': 'correct',`
`                  'to': '06155423',`
`                  'content': 'anycontent'}`
`        response = yield self.web.get("send", params)`
`         self.assertEqual(response.responseCode, 200)`



Travis came back and errored w/ response code 200 != 500.  If I manually invoke the http service (e.g. curl http://127.0.0.1:1401/send? . . .) without the sdt parameter I get a 200 OK and not a 500.  Obviously my "know enough to be deadly" view of Travis is getting into my way.  Any ideas on what I might be doing wrong?

Thanks again!

@JamuelStarkey

**Comment by farirat** [comment]
@JamuelStarkey please get in on slack and let's discuss this

**Comment by JamuelStarkey** [comment]
@farirat I've added the additional test coverage and functionality in authorizations.  All Travis tests are passing now.  The only thing that remains is for me to figure out how to rebase the PR so that all of my individual commits are squashed down to something a little more meaningful.

Please let me know what the best next step is otherwise let me know what's a good time to catch up with you on Slack.

**Pull request merged**
