### PR TITLE
[WIP] Sending custom TLV's with SubmitSm

### PR DESCRIPTION
**Pull request by terrycain**
## Overview:
I added basic logic to the `/send` HTTP API endpoint so it could receive JSON, and quick hack to make the values from the JSON fit through the UrlValidator. 

Then as all the optional parameter tag's are hard coded in a class, I passed in via the JSON a list of `tag_number`, `length`, `field_type` and `value`, which ends up in the SubmitSM PDU as a "raw_tlv". Once the PDU is ready for being sent over the wire, any raw TLV's are assembled and appended to the PDU body, then the header will be calculated correctly.

Normal operation of `/send` is not affected by this and even the JSON mode will work normally unless a `custom_tlv` key is provided

## Why:
Recently I've needed to provide some extra TLV's for MT SMS providing information to the SMPP provider on where to route messages. + JSON is nice.

## Testing:
I've added a few tests that do a simple HTTP POST with a JSON body (modifying the test harness to allow providing a JSON dict and headers). Also if jasmind.py is ran you can run the following curl command and inspect the SMPP packet going over the wire:
```
curl -i -H 'Content-Type: application/json' -XPOST -d '{"username": "test1", "password": "test1", "from": "TEST1", "to": "012345678901", "content": "test1234", "custom_tlvs": [ [12288, null, "COctetString", "some_value"] ]}'
```
The null representing length would mean that the TLV is of variable length.

## ToDo:
* Clean up code
* Write tests for the raw tlv logic
* Preferably fix the request.args output so values that are not lists are not encapsulated by lists
* And update the UrlValidator to validate custom_tlv json structure

---

It's at a state where it works, but it needs cleaning up.

Does this look OK to you guys or is this not something you wish to pursue?

### CODE REVIEW

**Comment by farirat** [comment]
Hey @terrycain 

Reviewing your pr, a great way to introduce tlv to a high level api (http) ! thanks for this contrib.

Could you please update the docs with the additional parameters and an example of how to use this ?

**Comment by terrycain** [comment]
Sure :smile:, am busy for the next couple of days but I'll add it to my list. Do you guys mind if I also PR adding JSON support to various parts of the HTTP API?

**Comment by farirat** [comment]
Hey there, are you aware of the rest api ? it's a full json restful api wrapping around the basic http api.

**Comment by terrycain** [comment]
What! I completely missed that :smile:. In that case, I'll have a look over the rest api and make sure that also works when providing TLVs, I was thinking adding an option to the dlr for a json response, that sound ok? Then if using the rest api, all the communication would be json.

**Comment by rajeevkk32** [comment]
How to make this work in SMPP client & Server.
I need to intercept Custom TLV params

**Pull request merged**
